import type { ProfileCard } from './types'

/**
 * Development fixtures so the app runs before Supabase is provisioned.
 *
 * These people are invented. Names follow real Surti/Khambhati/Ahmedabadi/
 * Indori Khatri surname patterns so filters, sorting and the mosal exogamy
 * rule can be exercised realistically — but no one from the source WhatsApp
 * transcript appears here, and no real contact details exist in this file.
 */
export const FIXTURE_PROFILES: ProfileCard[] = [
  {
    id: '00000000-0000-4000-8000-000000000001',
    publicRef: 'KH-1001',
    status: 'active',
    fullNameGu: 'જીગર કિરીટભાઈ રંગૂનવાલા',
    fullNameEn: 'Jigar Kiritbhai Rangoonwala',
    gender: 'male',
    ageYears: 29,
    heightCm: 173,
    city: 'સુરત',
    educationDetail: 'B.E. Computer Engineering',
    occupationDetail: 'Software Engineer, TCS (Adajan)',
    maritalStatus: 'never_married',
    subCommunityCode: 'surti',
    subCommunityGu: 'સુરતી ખત્રી',
    subCommunityEn: 'Surti Khatri',
    sectCode: 'jagat',
    sectGu: 'જગત',
    sectEn: 'Jagat',
    mosalName: 'નવનીતલાલ ગોરધનદાસ કંસારીવાલા',
    mosalSurname: 'Kansariwala',
    paternalSurname: 'Rangoonwala',
    fatherName: 'કિરીટભાઈ મનસુખલાલ રંગૂનવાલા',
    motherName: 'ભાવના કિરીટભાઈ રંગૂનવાલા',
    rashi: 'vrishabh',
    gan: 'manushya',
    mangal: 'none',
    astroConfidence: 'high',
    photoKey: null,
    photoBlurKey: null,
    photoUnlocked: false,
    dob: '1997-02-14',
    birthTime: '07:20',
    birthPlaceText: 'સુરત',
    nativePlace: 'સુરત',
  },
  {
    id: '00000000-0000-4000-8000-000000000002',
    publicRef: 'KH-1002',
    status: 'active',
    fullNameGu: 'હાર્દિક ભરતભાઈ વખારીયા',
    fullNameEn: 'Hardik Bharatbhai Vakhariya',
    gender: 'male',
    ageYears: 31,
    heightCm: 168,
    city: 'સુરત',
    educationDetail: 'B.Com',
    occupationDetail: 'પોતાનો કાપડનો ધંધો, રીંગ રોડ',
    maritalStatus: 'never_married',
    subCommunityCode: 'surti',
    subCommunityGu: 'સુરતી ખત્રી',
    subCommunityEn: 'Surti Khatri',
    sectCode: 'bhagat',
    sectGu: 'ભગત',
    sectEn: 'Bhagat',
    mosalName: 'પ્રફુલચંદ્ર મણિલાલ ગોનાવાલા',
    mosalSurname: 'Gonawala',
    paternalSurname: 'Vakhariya',
    fatherName: 'ભરતભાઈ ચીમનલાલ વખારીયા',
    motherName: 'રેખા ભરતભાઈ વખારીયા',
    rashi: 'kark',
    gan: 'dev',
    mangal: 'high',
    astroConfidence: 'medium',
    photoKey: null,
    photoBlurKey: null,
    photoUnlocked: false,
    dob: '1995-07-03',
    birthTime: '21:45',
    birthPlaceText: 'સુરત',
    nativePlace: 'સુરત',
  },
  {
    id: '00000000-0000-4000-8000-000000000003',
    publicRef: 'KH-1003',
    status: 'active',
    fullNameGu: 'દેવાંગ અશોકભાઈ કાપડીયા',
    fullNameEn: 'Devang Ashokbhai Kapadia',
    gender: 'male',
    ageYears: 27,
    heightCm: 178,
    city: 'અમદાવાદ',
    educationDetail: 'M.Pharm',
    occupationDetail: 'QA Officer, Zydus Lifesciences',
    maritalStatus: 'never_married',
    subCommunityCode: 'ahmedabadi',
    subCommunityGu: 'અમદાવાદી ખત્રી',
    subCommunityEn: 'Ahmedabadi Khatri',
    sectCode: 'jagat',
    sectGu: 'જગત',
    sectEn: 'Jagat',
    mosalName: 'ચંદ્રકાંત જયંતિલાલ દેગડાવાલા',
    mosalSurname: 'Degdawala',
    paternalSurname: 'Kapadia',
    fatherName: 'અશોકભાઈ નટવરલાલ કાપડીયા',
    motherName: 'મીના અશોકભાઈ કાપડીયા',
    rashi: 'tula',
    gan: 'dev',
    mangal: 'none',
    astroConfidence: 'high',
    photoKey: null,
    photoBlurKey: null,
    photoUnlocked: false,
    dob: '1999-10-08',
    birthTime: '05:15',
    birthPlaceText: 'અમદાવાદ',
    nativePlace: 'અમદાવાદ',
  },
  {
    id: '00000000-0000-4000-8000-000000000004',
    publicRef: 'KH-1004',
    status: 'active',
    fullNameGu: 'મિલન નિલેશભાઈ ગલ્લેદાર',
    fullNameEn: 'Milan Nileshbhai Galledar',
    gender: 'male',
    ageYears: 33,
    heightCm: 165,
    city: 'સુરત',
    educationDetail: 'Diploma Mechanical',
    occupationDetail: 'પોતાનું વર્કશોપ, કતારગામ',
    maritalStatus: 'never_married',
    subCommunityCode: 'surti',
    subCommunityGu: 'સુરતી ખત્રી',
    subCommunityEn: 'Surti Khatri',
    sectCode: 'bhagat',
    sectGu: 'ભગત',
    sectEn: 'Bhagat',
    mosalName: 'દિલીપભાઈ રતિલાલ પસીયાવાલા',
    mosalSurname: 'Pasiyawala',
    paternalSurname: 'Galledar',
    fatherName: 'નિલેશભાઈ કાંતિલાલ ગલ્લેદાર',
    motherName: 'જ્યોત્સના નિલેશભાઈ ગલ્લેદાર',
    rashi: 'makar',
    gan: 'rakshas',
    mangal: 'unknown',
    astroConfidence: 'low',
    photoKey: null,
    photoBlurKey: null,
    photoUnlocked: false,
    dob: '1993-01-22',
    birthTime: null,
    birthPlaceText: 'સુરત',
    nativePlace: 'સુરત',
  },
  {
    id: '00000000-0000-4000-8000-000000000005',
    publicRef: 'KH-1005',
    status: 'active',
    fullNameGu: 'કૃપા રજનીકાંત પસીયાવાલા',
    fullNameEn: 'Krupa Rajnikant Pasiyawala',
    gender: 'female',
    ageYears: 26,
    heightCm: 160,
    city: 'સુરત',
    educationDetail: 'M.Sc. Microbiology',
    occupationDetail: 'Lab In-charge, Unipath Diagnostics',
    maritalStatus: 'never_married',
    subCommunityCode: 'surti',
    subCommunityGu: 'સુરતી ખત્રી',
    subCommunityEn: 'Surti Khatri',
    sectCode: 'jagat',
    sectGu: 'જગત',
    sectEn: 'Jagat',
    mosalName: 'હસમુખલાલ ચુનીલાલ જરીવાલા',
    mosalSurname: 'Jariwala',
    paternalSurname: 'Pasiyawala',
    fatherName: 'રજનીકાંત મગનલાલ પસીયાવાલા',
    motherName: 'દક્ષા રજનીકાંત પસીયાવાલા',
    rashi: 'meen',
    gan: 'dev',
    mangal: 'none',
    astroConfidence: 'high',
    photoKey: null,
    photoBlurKey: null,
    photoUnlocked: false,
    dob: '2000-03-30',
    birthTime: '14:05',
    birthPlaceText: 'સુરત',
    nativePlace: 'સુરત',
  },
  {
    id: '00000000-0000-4000-8000-000000000006',
    publicRef: 'KH-1006',
    status: 'active',
    fullNameGu: 'નિધિ સંજયભાઈ ગોનાવાલા',
    fullNameEn: 'Nidhi Sanjaybhai Gonawala',
    gender: 'female',
    ageYears: 28,
    heightCm: 157,
    city: 'સુરત',
    educationDetail: 'B.Ed., B.A. Gujarati',
    occupationDetail: 'પ્રાથમિક શિક્ષિકા, નગર પ્રાથમિક શાળા',
    maritalStatus: 'never_married',
    subCommunityCode: 'surti',
    subCommunityGu: 'સુરતી ખત્રી',
    subCommunityEn: 'Surti Khatri',
    sectCode: 'bhagat',
    sectGu: 'ભગત',
    sectEn: 'Bhagat',
    mosalName: 'કનૈયાલાલ પોપટલાલ ભાણાભગવાનવાલા',
    mosalSurname: 'Bhanabhagwanwala',
    paternalSurname: 'Gonawala',
    fatherName: 'સંજયભાઈ રમણલાલ ગોનાવાલા',
    motherName: 'હંસા સંજયભાઈ ગોનાવાલા',
    rashi: 'simha',
    gan: 'manushya',
    mangal: 'low',
    astroConfidence: 'medium',
    photoKey: null,
    photoBlurKey: null,
    photoUnlocked: false,
    dob: '1998-08-17',
    birthTime: '18:30',
    birthPlaceText: 'સુરત',
    nativePlace: 'સુરત',
  },
  {
    id: '00000000-0000-4000-8000-000000000007',
    publicRef: 'KH-1007',
    status: 'active',
    fullNameGu: 'શ્રેયા મુકેશભાઈ દેગડાવાલા',
    fullNameEn: 'Shreya Mukeshbhai Degdawala',
    gender: 'female',
    ageYears: 25,
    heightCm: 163,
    city: 'વડોદરા',
    educationDetail: 'B.Arch',
    occupationDetail: 'Junior Architect, Studio Kaya',
    maritalStatus: 'never_married',
    subCommunityCode: 'khambhati',
    subCommunityGu: 'ખંભાતી ખત્રી',
    subCommunityEn: 'Khambhati Khatri',
    sectCode: 'jagat',
    sectGu: 'જગત',
    sectEn: 'Jagat',
    mosalName: 'વિનોદરાય શાંતિલાલ કાપડીયા',
    mosalSurname: 'Kapadia',
    paternalSurname: 'Degdawala',
    fatherName: 'મુકેશભાઈ ધીરજલાલ દેગડાવાલા',
    motherName: 'અલ્પા મુકેશભાઈ દેગડાવાલા',
    rashi: 'mithun',
    gan: 'dev',
    mangal: 'none',
    astroConfidence: 'high',
    photoKey: null,
    photoBlurKey: null,
    photoUnlocked: false,
    dob: '2001-05-11',
    birthTime: '09:50',
    birthPlaceText: 'વડોદરા',
    nativePlace: 'ખંભાત',
  },
  {
    id: '00000000-0000-4000-8000-000000000008',
    publicRef: 'KH-1008',
    status: 'active',
    fullNameGu: 'પલક હિતેશભાઈ કંસારીવાલા',
    fullNameEn: 'Palak Hiteshbhai Kansariwala',
    gender: 'female',
    ageYears: 30,
    heightCm: 155,
    city: 'ઇન્દોર',
    educationDetail: 'C.A.',
    occupationDetail: 'Practising Chartered Accountant',
    maritalStatus: 'never_married',
    subCommunityCode: 'indori',
    subCommunityGu: 'ઈન્દોરી ખત્રી',
    subCommunityEn: 'Indori Khatri',
    sectCode: 'bhagat',
    sectGu: 'ભગત',
    sectEn: 'Bhagat',
    mosalName: 'ગિરીશભાઈ મગનલાલ રંગૂનવાલા',
    mosalSurname: 'Rangoonwala',
    paternalSurname: 'Kansariwala',
    fatherName: 'હિતેશભાઈ સુરેશચંદ્ર કંસારીવાલા',
    motherName: 'વર્ષા હિતેશભાઈ કંસારીવાલા',
    rashi: 'vrishchik',
    gan: 'rakshas',
    mangal: 'high',
    astroConfidence: 'high',
    photoKey: null,
    photoBlurKey: null,
    photoUnlocked: false,
    dob: '1996-11-25',
    birthTime: '23:10',
    birthPlaceText: 'ઇન્દોર',
    nativePlace: 'ઇન્દોર',
  },
]
